### ISSUE TITLE
[device port] port to ASUS Zenfone max pro m1

### ISSUE THREAD

**Issue by alexpseletr** [Halium/projectmanagement#138]
Tree: 

- [ ] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_recorder

**Comment by ghost** [comment]
Bro is it complete for testing

**Comment by iwan-beep** [comment]
can it be tested?

**Comment by ramasai-badam** [comment]
Hello @alexpseletr are you currently making any progress in this ?

**Comment by SentryGA** [comment]
@alexpseletr are you still working on the port, could you share your progress? I might be of some help was planning to do it myself till i found this.

**Comment by KthulhuFtaghn** [comment]
seems inactive. i was gonna start working on a port, if any of you wish to join me.. email me at appcoin.news@gmail.com

**Comment by ramasai-badam** [comment]
I have no knowledge on porting but know some Linux commands and how to
use terminal and programming .Let me know how can i help porting Ubuntu touch for Asus.

**Comment by SentryGA** [comment]
I enquired in the halium telegram group they said that it only had support upto android 7, this means max pro m1 won't have support because it started at oreo. They asked me to wait or help them with developing halium for Android 8 support. There are instructions I can understand on how to port but I do not much understand how halium is made  I am not that capable, so thought of waiting for it.

**Comment by doniks** [comment]
if someone ever gets anywhere with a port and at least has a manifest, I suggest you create a new issue and link said manifest
