### ISSUE TITLE
Android 9 support

### ISSUE THREAD

**Issue by GeorgeGhost** [Halium/projectmanagement#148]
There is halium 7.1 and halium 5.1, but what should you do when porting halium to android 9 device?

**Comment by jbruechert** [comment]
There is a halium 8.1 tree being developed by @Herrie82, which will be enough for most devices. We are currently reusing the mer-hybris trees, meaning that we will likely wait for mer with creating an halium-9 tree.

**Comment by hacker1024** [comment]
Could @Herrie82's tree be used to create a GSI?

**Comment by Herrie82** [comment]
@hacker1024 What is GSI? The Android 8.1 was just build tested and it still failed for me in the last step, but most of the hard work should've been done really. Creating 9.1 would be possible as well. Just that the Mer guys took a different approach and aren't disabling all unnecessary Java stuff anymore like it was done with 5.1 and 7.1. So in order to create a 8.1/9.1 tree, it required quite some fiddling to disable these bits again.

**Comment by basxto** [comment]
Generic System Images are not built for specific devices and instead run on hardware abstraction layer of Project Treble, which got introduced with Oreo. It seperates Android and the drivers of the chipset makers.

https://github.com/phhusson/treble_experimentations/wiki/Generic-System-Image-(GSI)-list
